#!/usr/bin/env node
// Demo content for a provisioned hotel (docs/pilot/README.md §4), so the platform can be tried end to end before the
// hotel's real data arrives. Everything comes from a demo file next to the hotel's profile; every name in it is
// fictional. Run as a platform administrator after `pilot.sh provision`:
//
//   1. brand: name, colours, contact, welcome texts (platform administrator);
//   2. staff accounts, one per role, with generated passwords kept in the accounts file (0600), never printed;
//   3. as the demo general manager — the hotel's own content, which a platform administrator may not touch (Spec §64):
//      the starter services, à la carte restaurants with their sittings, and hotel information for the AI concierge;
//   4. a simulated PMS connector with a one-time enrollment code and a stay scenario dated from today, which
//      `pilot.sh demo` replays with the PMS simulator so the hotel has guests in house.
//
// Idempotent: what exists (by e-mail, code, title or name) is kept. Nothing here is used once the hotel is live; the
// README of the hotel says how to remove it.
//
//   node demo-content.mjs --api <url> --dir <state dir> <profile.json> <demo.json>     (token: $HOTELLA_TOKEN)

import { randomBytes } from 'node:crypto';
import { chmodSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const LOCALES = ['en', 'ar', 'it', 'ru', 'de'];
const SIM_CAPABILITIES = [
  'CHECKIN_EVENT',
  'CHECKOUT_EVENT',
  'ROOM_MOVE_EVENT',
  'PROFILE_EVENT',
  'ROOM_STATUS_READ',
  'RESERVATION_READ',
  'GUEST_READ',
  'RECONCILIATION_READ',
];

/** The problems of a demo file (empty when it can be applied). */
export function validateDemo(demo, profile) {
  const problems = [];
  const need = (cond, msg) => cond || problems.push(msg);
  need(demo?.demoVersion === 1, 'demoVersion must be 1');
  const rooms = new Set();
  for (const b of profile?.buildings ?? [])
    for (const f of b.floors ?? [])
      for (const r of f.rooms ?? [])
        if (typeof r.number === 'string') rooms.add(r.number);
        else for (let n = r.from; n <= r.to; n++) rooms.add(String(n));
  const staff = demo?.staff ?? [];
  need(
    staff.filter((s) => s.role === 'GENERAL_MANAGER' && s.scope === 'TENANT').length === 1,
    'staff: exactly one GENERAL_MANAGER with scope TENANT (the demo content is entered as that person)',
  );
  const emails = new Set();
  for (const [i, s] of staff.entries()) {
    need(/^[^@\s]+@[^@\s]+\.[a-z]{2,}$/.test(s.email ?? ''), `staff[${i}].email`);
    need(!emails.has(s.email), `staff[${i}]: duplicate e-mail`);
    emails.add(s.email);
    need(typeof s.givenName === 'string' && s.givenName.trim(), `staff[${i}].givenName`);
    need(/^[A-Z][A-Z0-9_]{1,63}$/.test(s.role ?? ''), `staff[${i}].role`);
    need(LOCALES.includes(s.locale), `staff[${i}].locale`);
  }
  for (const [i, r] of (demo?.restaurants ?? []).entries()) {
    need(/^[A-Z][A-Z0-9_-]{1,31}$/.test(r.code ?? ''), `restaurants[${i}].code`);
    need(typeof r.names?.en === 'string', `restaurants[${i}].names.en`);
    need(
      (r.sittings ?? []).every((t) => /^([01]\d|2[0-3]):[0-5]\d$/.test(t)),
      `restaurants[${i}].sittings: HH:MM`,
    );
    need(Number.isInteger(r.seats) && r.seats > 0, `restaurants[${i}].seats`);
  }
  for (const [i, d] of (demo?.knowledge ?? []).entries()) {
    need(typeof d.title === 'string' && d.title.trim(), `knowledge[${i}].title`);
    need((d.versions ?? []).length > 0, `knowledge[${i}].versions`);
  }
  for (const [i, g] of (demo?.pms?.guests ?? []).entries()) {
    need(rooms.has(g.room), `pms.guests[${i}].room ${g.room} is not a room of the profile`);
    need(['IN_HOUSE', 'ARRIVING', 'CHECKED_OUT'].includes(g.state), `pms.guests[${i}].state`);
    need(
      Number.isInteger(g.arrival) && Number.isInteger(g.nights) && g.nights > 0,
      `pms.guests[${i}]: arrival, nights`,
    );
    need(
      g.state !== 'ARRIVING' || g.arrival >= 0,
      `pms.guests[${i}]: an arriving guest arrives today or later`,
    );
  }
  return problems;
}

const addDays = (day, n) => {
  const d = new Date(`${day}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + n);
  return d.toISOString().slice(0, 10);
};
const q = (s) => JSON.stringify(String(s));

/** The PMS simulator scenario for the demo stays, dated from `today` (the hotel's date). */
export function demoScenario(demo, profile, today) {
  const lines = [
    '# Generated by demo-content.mjs: fictional demo stays (docs/pilot/README.md §4).',
    `name: ${q(`${profile.property.name} demo stays`)}`,
    `timezone: ${q(profile.property.timezone)}`,
    'faces: [FIAS, OWS]',
    'steps:',
  ];
  for (const g of demo.pms?.guests ?? []) {
    const arrival = addDays(today, g.arrival);
    const departure = addDays(arrival, g.nights);
    lines.push(
      '  - reserve:',
      `      id: ${q(g.id)}`,
      `      confirmation: ${q(g.id)}`,
      `      guest: { profileId: ${q(`P-${g.id}`)}, first: ${q(g.first)}, last: ${q(g.last)}, language: ${q(g.language)} }`,
      `      arrival: ${q(arrival)}`,
      `      departure: ${q(g.state === 'CHECKED_OUT' ? today : departure)}`,
      `      room: ${q(g.room)}`,
    );
    if (g.state !== 'ARRIVING') lines.push(`  - checkin: { id: ${q(g.id)}, room: ${q(g.room)} }`);
    if (g.state === 'CHECKED_OUT') lines.push(`  - checkout: { id: ${q(g.id)} }`);
  }
  lines.push('  - wait_acked: {}', '');
  return lines.join('\n');
}

/** Today in the hotel's time zone. */
export function hotelToday(timezone, now = new Date()) {
  return new Intl.DateTimeFormat('en-CA', { timeZone: timezone }).format(now);
}

const password = () => randomBytes(18).toString('base64url');

/** Applies the demo content; returns counts and what `pilot.sh demo` needs next (never a password). */
export async function applyDemo(
  profile,
  demo,
  {
    api,
    token,
    accounts = {},
    fetchFn = fetch,
    log = () => {},
    today = hotelToday(profile.property.timezone),
  },
) {
  const base = api.replace(/\/+$/, '');
  const call = async (method, path, body, bearer = token) => {
    const res = await fetchFn(`${base}${path}`, {
      method,
      headers: { authorization: `Bearer ${bearer}`, 'content-type': 'application/json' },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    const text = await res.text();
    if (!res.ok)
      throw new Error(`${method} ${path.split('?')[0]} → ${res.status} ${text.slice(0, 300)}`);
    return text ? JSON.parse(text) : null;
  };
  const counts = {};
  const note = (what, created) => {
    counts[what] ??= { created: 0, existing: 0 };
    counts[what][created ? 'created' : 'existing']++;
  };

  const tenant = (await call('GET', '/tenants')).find((t) => t.code === profile.tenant.code);
  if (!tenant)
    throw new Error(`tenant ${profile.tenant.code} not found: run pilot.sh provision first`);
  const property = (await call('GET', `/properties?tenantId=${tenant.id}`)).find(
    (p) => p.code === profile.property.code,
  );
  if (!property)
    throw new Error(`property ${profile.property.code} not found: run pilot.sh provision first`);
  const p = `/properties/${property.id}`;
  log(`demo content for ${tenant.code}/${property.code}`);

  // 1. Brand (platform → tenant → property; the Planova footer stays, rule 15).
  if (demo.brand) {
    await call('PUT', `/branding/profiles?tenantId=${tenant.id}`, {
      scope: 'PROPERTY',
      scopeId: property.id,
      displayName: demo.brand.displayName,
      primaryColor: demo.brand.primaryColor,
      secondaryColor: demo.brand.secondaryColor,
      contact: demo.brand.contact ?? {},
      aiPersona: demo.brand.aiPersona ?? {},
      translations: Object.entries(demo.brand.welcome ?? {}).map(([locale, welcomeText]) => ({
        locale,
        welcomeText,
      })),
    });
    counts.brand = { applied: 1 };
  }

  // 2. Staff accounts: invited, then the invitation accepted with a generated password.
  const t = `/tenants/${tenant.id}`;
  const existing = new Set((await call('GET', `${t}/users`)).map((u) => u.email.toLowerCase()));
  for (const s of demo.staff ?? []) {
    const email = s.email.toLowerCase();
    note('staff', !existing.has(email));
    if (existing.has(email)) continue;
    const created = await call('POST', `${t}/users`, {
      email,
      givenName: s.givenName,
      ...(s.familyName ? { familyName: s.familyName } : {}),
      localePref: s.locale,
      memberships: [{ propertyId: s.scope === 'TENANT' ? null : property.id, roleCodes: [s.role] }],
    });
    const secret = password();
    await call('POST', '/auth/invitations/accept', {
      token: created.invitation.token,
      password: secret,
    });
    accounts[email] = { password: secret, role: s.role, hotelCode: tenant.code };
  }

  // 3. The hotel's content, entered as its demo general manager.
  const gm = (demo.staff ?? []).find((s) => s.role === 'GENERAL_MANAGER' && s.scope === 'TENANT');
  const gmAccount = gm && accounts[gm.email.toLowerCase()];
  let pending = null;
  if (!gmAccount) {
    log(`the demo general manager's password is not in the accounts file: hotel content skipped`);
  } else {
    const session = await call('POST', '/auth/login', {
      tenantCode: tenant.code,
      email: gm.email.toLowerCase(),
      password: gmAccount.password,
    });
    const as = (method, path, body) => call(method, path, body, session.accessToken);

    if (demo.starterCatalog) {
      const r = await as('POST', `${p}/catalog/starter`, {});
      counts.service = { created: r.created.length, existing: r.skipped.length };
    }

    const restaurants = new Set((await as('GET', `${p}/restaurants`)).map((r) => r.code));
    for (const r of demo.restaurants ?? []) {
      note('restaurant', !restaurants.has(r.code));
      if (restaurants.has(r.code)) continue;
      const created = await as('POST', `${p}/restaurants`, {
        code: r.code,
        maxParty: r.maxParty ?? 8,
        translations: LOCALES.filter((l) => r.names[l]).map((l) => ({
          locale: l,
          name: r.names[l],
          ...(r.dressCode?.[l] ? { dressCode: r.dressCode[l] } : {}),
        })),
      });
      await as('PUT', `${p}/restaurants/${created.id}/sittings`, {
        fromDate: today,
        sittings: [0, 1, 2, 3, 4, 5, 6].flatMap((weekday) =>
          r.sittings.map((startsAt) => ({ weekday, startsAt, seats: r.seats })),
        ),
      });
      const current = await as('GET', `${p}/restaurants/${created.id}`);
      await as('PATCH', `${p}/restaurants/${created.id}`, {
        version: current.version,
        status: 'ACTIVE',
      });
    }

    const documents = new Set((await as('GET', `${p}/knowledge/documents`)).map((d) => d.title));
    for (const d of demo.knowledge ?? []) {
      note('knowledge', !documents.has(d.title));
      if (documents.has(d.title)) continue;
      const doc = await as('POST', `${p}/knowledge/documents`, {
        kind: d.kind ?? 'FAQ',
        title: d.title,
      });
      for (const v of d.versions) {
        const version = await as('POST', `${p}/knowledge/documents/${doc.id}/versions`, {
          language: v.language,
          audience: v.audience ?? 'GUEST',
          classification: v.classification ?? 'PUBLIC',
          body: v.body,
        });
        await as('POST', `${p}/knowledge/documents/${doc.id}/versions/${version.id}/publish`);
      }
    }
  }

  // 4. A simulated PMS with demo stays (once: an existing connector of that name means it was done).
  if (demo.pms?.guests?.length) {
    const instances = await call('GET', `${p}/integrations`);
    const found = instances.find((i) => i.name === demo.pms.name);
    note('pms', !found);
    if (!found) {
      const instance = await call('POST', `${p}/integrations`, {
        connectorCode: 'SIM_PMS',
        name: demo.pms.name,
        capabilities: SIM_CAPABILITIES,
      });
      await call('PATCH', `${p}/integrations/${instance.id}`, {
        version: instance.version ?? 1,
        status: 'ACTIVE',
      });
      await call('POST', `${p}/integrations/${instance.id}/mappings/rooms-by-number`);
      const enrollment = await call('POST', `${p}/integrations/${instance.id}/enrollment-tokens`);
      pending = { enrollmentToken: enrollment.token, scenario: demoScenario(demo, profile, today) };
    }
  }
  return { tenantId: tenant.id, propertyId: property.id, counts, accounts, pending };
}

async function main(argv) {
  const args = argv.slice(2);
  const flag = (name) => {
    const i = args.indexOf(name);
    if (i < 0) return undefined;
    const v = args[i + 1];
    args.splice(i, 2);
    return v;
  };
  const api = flag('--api') ?? 'http://localhost:3000/api/v1';
  const dir = flag('--dir');
  const token = process.env.HOTELLA_TOKEN;
  const [profileFile, demoFile] = args;
  if (!dir || !profileFile || !demoFile)
    throw new Error(
      'usage: demo-content.mjs --api <url> --dir <state dir> <profile.json> <demo.json>',
    );
  if (!token) throw new Error('a platform administrator token is needed ($HOTELLA_TOKEN)');
  const profile = JSON.parse(readFileSync(profileFile, 'utf8'));
  const demo = JSON.parse(readFileSync(demoFile, 'utf8'));
  const problems = validateDemo(demo, profile);
  if (problems.length) {
    process.stderr.write(`demo file ${demoFile} is not valid:\n- ${problems.join('\n- ')}\n`);
    process.exit(2);
  }
  const accountsFile = join(dir, 'accounts.json');
  const accounts = existsSync(accountsFile) ? JSON.parse(readFileSync(accountsFile, 'utf8')) : {};
  const save = () => {
    writeFileSync(accountsFile, `${JSON.stringify(accounts, null, 2)}\n`, { mode: 0o600 });
    chmodSync(accountsFile, 0o600);
  };
  let result;
  try {
    result = await applyDemo(profile, demo, {
      api,
      token,
      accounts,
      log: (l) => process.stdout.write(`${l}\n`),
    });
  } finally {
    save(); // accounts created before a failure keep their passwords
  }
  if (result.pending) {
    writeFileSync(join(dir, 'enrollment-token'), `${result.pending.enrollmentToken}\n`, {
      mode: 0o600,
    });
    writeFileSync(join(dir, 'scenario.yml'), result.pending.scenario, { mode: 0o644 });
  }
  process.stdout.write(
    `result ${JSON.stringify({ tenantId: result.tenantId, propertyId: result.propertyId, counts: result.counts, simulate: !!result.pending })}\n`,
  );
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href)
  main(process.argv).catch((e) => {
    process.stderr.write(`demo content failed: ${e.message}\n`);
    process.exit(1);
  });
