export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      1,
      'always',
      [
        'repo',
        'ci',
        'docs',
        'deps',
        'tooling',
        'api',
        'worker',
        'realtime',
        'guest-web',
        'staff-web',
        'simulator',
        'agent',
        'config',
        'observability',
        'database',
        'events',
        'queue',
        'auth',
        'storage',
        'secrets',
        'i18n',
        'testing',
        'org',
        'iam',
        'guest',
        'catalog',
        'ops',
        'hk',
        'eng',
        'inspection',
        'relations',
        'lostfound',
        'logbook',
        'comms',
        'knowledge',
        'ai',
        'integration',
        'license',
        'audit',
        'contracts',
      ],
    ],
    'header-max-length': [2, 'always', 100],
  },
};
