// Generates the app's Dart API client from the platform's OpenAPI document (generated from the zod contracts,
// ADR-0005, ADR-0023): one method per operation the app uses, with its path and query parameters, and a Dart class per
// request body schema. Nothing here is written by hand; `--check` fails when the committed client is stale (CI).
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(process.cwd(), '..', '..');
const spec = JSON.parse(
  readFileSync(join(root, 'apps', 'api', 'test', '__snapshots__', 'openapi.json'), 'utf8'),
);
const target = join(process.cwd(), 'lib', 'api', 'hotella_api.g.dart');
const check = process.argv.includes('--check');
const PREFIX = '/api/v1';

/** The operations the staff app calls (by OpenAPI operation id) and the Dart method names they get. */
const OPERATIONS = {
  BrandingController_hotel: 'findHotel',
  AuthController_login: 'login',
  AuthController_verifyMfa: 'verifyMfa',
  AuthController_refresh: 'refresh',
  AuthController_logout: 'logout',
  MeController_me: 'me',
  MeController_registerDevice: 'registerDevice',
  MeController_revokeDevice: 'revokeDevice',
  PropertiesController_list: 'listProperties',
};

const ops = [];
for (const [path, methods] of Object.entries(spec.paths))
  for (const [method, op] of Object.entries(methods))
    if (OPERATIONS[op.operationId])
      ops.push({ path, method: method.toUpperCase(), op, name: OPERATIONS[op.operationId] });
const missing = Object.keys(OPERATIONS).filter((id) => !ops.some((o) => o.op.operationId === id));
if (missing.length) {
  console.error(`operations missing from the OpenAPI document: ${missing.join(', ')}`);
  process.exit(1);
}
ops.sort((a, b) => a.name.localeCompare(b.name));

const camel = (s) => s.replace(/[-_.](\w)/g, (_, c) => c.toUpperCase());
function dartType(schema) {
  if (!schema) return 'Object';
  if (schema.$ref) return schema.$ref.split('/').pop();
  switch (schema.type) {
    case 'string':
      return 'String';
    case 'integer':
      return 'int';
    case 'number':
      return 'num';
    case 'boolean':
      return 'bool';
    case 'array':
      return `List<${dartType(schema.items)}>`;
    default:
      return 'Map<String, Object?>';
  }
}

// Request body classes.
const bodies = new Map();
for (const { op } of ops) {
  const ref = op.requestBody?.content?.['application/json']?.schema?.$ref;
  if (ref) bodies.set(ref.split('/').pop(), spec.components.schemas[ref.split('/').pop()]);
}

const lines = [
  '// GENERATED by tool/gen_client.mjs from apps/api/test/__snapshots__/openapi.json — do not edit by hand.',
  '// ignore_for_file: type=lint',
  '',
  "import 'transport.dart';",
  '',
];
for (const [name, schema] of [...bodies].sort(([a], [b]) => a.localeCompare(b))) {
  const required = new Set(schema.required ?? []);
  const fields = Object.entries(schema.properties ?? {}).map(([key, s]) => ({
    key,
    field: camel(key),
    type: dartType(s),
    required: required.has(key),
  }));
  lines.push(`/// Request body \`${name}\`.`, `class ${name} {`);
  lines.push(
    `  const ${name}({${fields.map((f) => `${f.required ? 'required ' : ''}this.${f.field}`).join(', ')}});`,
  );
  for (const f of fields) lines.push(`  final ${f.type}${f.required ? '' : '?'} ${f.field};`);
  lines.push('', '  Map<String, Object?> toJson() => {');
  for (const f of fields)
    lines.push(
      f.required
        ? `        '${f.key}': ${f.field},`
        : `        if (${f.field} != null) '${f.key}': ${f.field},`,
    );
  lines.push('      };', '}', '');
}

lines.push(
  '/// The platform API operations the app uses (`/api/v1`).',
  'class HotellaApi {',
  '  HotellaApi(this.transport);',
  '  final ApiTransport transport;',
  '',
);
for (const { path, method, op, name } of ops) {
  const params = (op.parameters ?? []).filter((p) => p.in === 'path' || p.in === 'query');
  const pathParams = params.filter((p) => p.in === 'path');
  const query = params.filter((p) => p.in === 'query');
  const body = op.requestBody?.content?.['application/json']?.schema?.$ref?.split('/').pop();
  const args = [
    ...pathParams.map((p) => `String ${camel(p.name)}`),
    ...(body ? [`${body} body`] : []),
  ];
  const named = query.map(
    (p) => `${p.required ? 'required ' : ''}String${p.required ? '' : '?'} ${camel(p.name)}`,
  );
  const signature = [...args, ...(named.length ? [`{${named.join(', ')}}`] : [])].join(', ');
  const url = path
    .slice(PREFIX.length)
    .replace(/\{(\w+)\}/g, (_, p) => `\${Uri.encodeComponent(${camel(p)})}`);
  const q = query.length
    ? `, query: {${query.map((p) => `'${p.name}': ${camel(p.name)}`).join(', ')}}`
    : '';
  lines.push(
    `  /// \`${method} ${path}\` (${op.operationId}).`,
    `  Future<Object?> ${name}(${signature}) =>`,
    `      transport.send('${method}', '${url}'${body ? ', body: body.toJson()' : ''}${q});`,
    '',
  );
}
if (lines.at(-1) === '') lines.pop();
lines.push('}', '');
const text = lines.join('\n');

if (check) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== text) {
    console.error(`stale: ${target} — run \`node tool/gen_client.mjs\` in apps/mobile`);
    process.exit(1);
  }
  console.log('Dart client check OK');
} else {
  writeFileSync(target, text);
  console.log(`Dart client written — ${ops.length} operations, ${bodies.size} request bodies`);
}
