// GENERATED by tool/gen_client.mjs from apps/api/test/__snapshots__/openapi.json — do not edit by hand.
// ignore_for_file: type=lint

import 'transport.dart';

/// Request body `LoginDto`.
class LoginDto {
  const LoginDto({this.tenantCode, required this.email, required this.password});
  final String? tenantCode;
  final String email;
  final String password;

  Map<String, Object?> toJson() => {
        if (tenantCode != null) 'tenantCode': tenantCode,
        'email': email,
        'password': password,
      };
}

/// Request body `MfaVerifyDto`.
class MfaVerifyDto {
  const MfaVerifyDto({required this.challengeToken, required this.code});
  final String challengeToken;
  final String code;

  Map<String, Object?> toJson() => {
        'challengeToken': challengeToken,
        'code': code,
      };
}

/// Request body `RefreshDto`.
class RefreshDto {
  const RefreshDto({required this.refreshToken});
  final String refreshToken;

  Map<String, Object?> toJson() => {
        'refreshToken': refreshToken,
      };
}

/// Request body `RegisterDeviceDto`.
class RegisterDeviceDto {
  const RegisterDeviceDto({required this.platform, required this.pushToken, this.appVersion, this.locale});
  final String platform;
  final String pushToken;
  final String? appVersion;
  final String? locale;

  Map<String, Object?> toJson() => {
        'platform': platform,
        'pushToken': pushToken,
        if (appVersion != null) 'appVersion': appVersion,
        if (locale != null) 'locale': locale,
      };
}

/// The platform API operations the app uses (`/api/v1`).
class HotellaApi {
  HotellaApi(this.transport);
  final ApiTransport transport;

  /// `GET /api/v1/public/hotels/{code}` (BrandingController_hotel).
  Future<Object?> findHotel(String code) =>
      transport.send('GET', '/public/hotels/${Uri.encodeComponent(code)}');

  /// `GET /api/v1/properties` (PropertiesController_list).
  Future<Object?> listProperties({String? tenantId}) =>
      transport.send('GET', '/properties', query: {'tenantId': tenantId});

  /// `POST /api/v1/auth/login` (AuthController_login).
  Future<Object?> login(LoginDto body) =>
      transport.send('POST', '/auth/login', body: body.toJson());

  /// `POST /api/v1/auth/logout` (AuthController_logout).
  Future<Object?> logout() =>
      transport.send('POST', '/auth/logout');

  /// `GET /api/v1/me` (MeController_me).
  Future<Object?> me() =>
      transport.send('GET', '/me');

  /// `POST /api/v1/auth/refresh` (AuthController_refresh).
  Future<Object?> refresh(RefreshDto body) =>
      transport.send('POST', '/auth/refresh', body: body.toJson());

  /// `POST /api/v1/me/devices` (MeController_registerDevice).
  Future<Object?> registerDevice(RegisterDeviceDto body) =>
      transport.send('POST', '/me/devices', body: body.toJson());

  /// `DELETE /api/v1/me/devices/{deviceId}` (MeController_revokeDevice).
  Future<Object?> revokeDevice(String deviceId) =>
      transport.send('DELETE', '/me/devices/${Uri.encodeComponent(deviceId)}');

  /// `POST /api/v1/auth/mfa/verify` (AuthController_verifyMfa).
  Future<Object?> verifyMfa(MfaVerifyDto body) =>
      transport.send('POST', '/auth/mfa/verify', body: body.toJson());
}
