# OpenBao (KV v2 secret store; API-compatible with HashiCorp Vault — ADR-0013 revision). Pilot: single node,
# integrated Raft storage on a dedicated volume, TLS with the pilot CA generated by `pilot.sh init`.
ui            = false
disable_mlock = true
api_addr      = "https://openbao:8200"
cluster_addr  = "https://openbao:8201"

storage "raft" {
  path    = "/openbao/file"
  node_id = "openbao-1"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/openbao/tls/server.crt"
  tls_key_file  = "/openbao/tls/server.key"
}

# File audit device (docs/security/SECRETS_LIFECYCLE.md): every request with its identity, values HMAC-ed. Declared
# here because OpenBao 2.x does not let the API create audit devices (a compromised token must not redirect them).
audit "file" "file" {
  description = "Hotella pilot audit log"
  options {
    file_path = "/openbao/logs/audit.log"
  }
}
