# OpenBao (KV v2 secret store; API-compatible with HashiCorp Vault — ADR-0013 revision). Pilot: single node,
# integrated Raft storage on a dedicated volume, TLS with the pilot CA generated by `pilot.sh init`.
ui            = false
disable_mlock = true
api_addr      = "https://openbao:8200"
cluster_addr  = "https://openbao:8201"

storage "raft" {
  path    = "/openbao/file"
  node_id = "openbao-1"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/openbao/tls/server.crt"
  tls_key_file  = "/openbao/tls/server.key"
}
